plugins {
    id 'java-library'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}
description = 'pg'

dependencies {
    implementation project(":domain")
    implementation project(":infra:restTemplate")
    implementation project(":infra:retry")
    implementation 'org.springframework.boot:spring-boot-starter'
}
