import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'java'
    id "com.github.spotbugs" version "6.4.8" apply false
    id "io.spring.dependency-management" version "1.1.6" apply false
}

group = 'com.dragons'
version = '0.0.1-SNAPSHOT'

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {

    ext {
        lombokVersion = '1.18.34'
    }

    apply plugin: 'java'
    apply plugin: "com.github.spotbugs"
    apply plugin: "checkstyle"
    apply plugin: "io.spring.dependency-management"


    checkstyle {
        toolVersion = "13.0.0"
        configFile = rootProject.file("config/checkstyle/google_checks.xml")
        ignoreFailures = false
    }


    spotbugs {
        effort = "default"
        reportLevel = "high"
        ignoreFailures = false
    }


    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    // Apply Lombok to all submodules for both main and test sources
    dependencies {
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        constraints {
            implementation "org.bouncycastle:bcprov-jdk18on:1.83"
        }
    }


    tasks.withType(Checkstyle).configureEach {
        reports {
            html.required = true
            xml.required = false
        }
    }

    tasks.withType(SpotBugsTask).configureEach {
        reports {
            html.required = true
            xml.required = false
        }
    }

    tasks.withType(Test).configureEach {
        maxParallelForks = 1
        useJUnitPlatform()
        systemProperty("user.timezone", "Asia/Seoul")
        systemProperty("spring.profiles.active", "test")
        jvmArgs("-Xshare:off")
        testLogging {
            events "passed", "skipped", "failed"
            showStandardStreams = true
            exceptionFormat "full"
        }
    }

    // apps 모듈을 제외한 모든 서브프로젝트는 bootJar 비활성화
    plugins.withId('org.springframework.boot') {
        if (!project.path.startsWith(':apps:')) {
            tasks.named('bootJar') {
                enabled = false
            }
            tasks.named('jar') {
                enabled = true
            }
        }
    }
}



configure(subprojects) {
    plugins.withId('io.spring.dependency-management') {
        dependencyManagement {
            imports {
                mavenBom "org.testcontainers:testcontainers-bom:1.19.8"
            }
        }
    }
}
