

plugins {
    id 'java'
    id "com.github.spotbugs" version "6.4.8" apply false
}

group = 'com.dragons'
version = '0.0.1-SNAPSHOT'

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: "com.github.spotbugs"

    spotbugs {
        effort = "default"
        reportLevel = "high"
        ignoreFailures = false
    }


    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    // Apply Lombok to all submodules for both main and test sources
    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.34'
        annotationProcessor 'org.projectlombok:lombok:1.18.34'

        testCompileOnly 'org.projectlombok:lombok:1.18.34'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
    }

    tasks.withType(com.github.spotbugs.snom.SpotBugsTask).configureEach {
        reports {
            html.required = true
            xml.required = false
        }
    }

    tasks.withType(Test).configureEach {
        maxParallelForks = 1
        useJUnitPlatform()
        systemProperty("user.timezone", "Asia/Seoul")
        systemProperty("spring.profiles.active", "test")
        jvmArgs("-Xshare:off")
        testLogging {
            events "passed", "skipped", "failed"
            showStandardStreams = true
            exceptionFormat "full"
        }
    }

    // apps 모듈을 제외한 모든 서브프로젝트는 bootJar 비활성화
    plugins.withId('org.springframework.boot') {
        if (!project.path.startsWith(':apps:')) {
            tasks.named('bootJar') {
                enabled = false
            }
            tasks.named('jar') {
                enabled = true
            }
        }
    }
}



configure(subprojects) {
    plugins.withId('io.spring.dependency-management') {
        dependencyManagement {
            imports {
                mavenBom "org.testcontainers:testcontainers-bom:2.0.1"
            }
        }
    }
}
