spring:
  application:
    name: dragons
  config:
    import:
      - logging.yml
      - jwt.yml
      - optional:redis.yml
      - jpa.yml
      - social.yml
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
      timeout: 30m
  port: 8082
datasource:
  redis:
    enabled: false
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  hello: ????
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: local
  hello: ????
server:
  port: 8089
---
